/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-06-21 04:12:19 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/reloaded -t endereco -s public
 *
 */



    export type id = number;
    export type rua = string | null;
    export type logradouro = string | null;
    export type complemento = string | null;
    export type numero = number | null;
    export type uf = string | null;
    export type cep = string | null;
    export type avenida = string | null;
    export type cidade = string | null;
    export type bairro = string | null;
    export type fk_imovel_id = number | null;
    export type created_at = Date | null;
    export type updated_at = Date | null;

export interface Endereco {
    id: id;
    rua: rua;
    logradouro: logradouro;
    complemento: complemento;
    numero: numero;
    uf: uf;
    cep: cep;
    avenida: avenida;
    cidade: cidade;
    bairro: bairro;
    fk_imovel_id: fk_imovel_id;
    created_at: created_at;
    updated_at: updated_at;

}
