/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-06-21 04:28:11 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/reloaded -t pessoa_endereco -s public
 *
 */



    export type fk_pessoa_id = number | null;
    export type fk_endereco_id = number | null;

export interface PessoaEndereco {
    fk_pessoa_id: fk_pessoa_id;
    fk_endereco_id: fk_endereco_id;

}
