/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2020-06-21 04:29:06 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/reloaded -t vistoria -s public
 *
 */


    export type id = number;
    export type observacao = string | null;
    export type created_at = Date | null;
    export type fk_pessoa_id = number | null;
    export type fk_imovel_id = number | null;

export interface Vistoria {
    id: id;
    observacao: observacao;
    created_at: created_at;
    fk_pessoa_id: fk_pessoa_id;
    fk_imovel_id: fk_imovel_id;

}
