import Vue from "vue";

export default new Vue();

export const TYPES = { 
  START_UPLOAD: "START_UPLOAD",
  START_UPLOAD_DOCS: "START_UPLOAD_DOCS",
  REFRESH_LIST_MIDIAS: "REFRESH_LIST_MIDIAS",
  REFRESH_LIST_DOCS: "REFRESH_LIST_DOCS"
}